export const TestData = {
    site: 'https://petstore.octoperf.com/actions/Catalog.action',
    username: `2002`,
    password: `Emir123`,
    productId: 'AV-CB-01',
    productIdDog: 'K9-BD-01',
    alt: 'Birds',
    src: '../images/birds_icon.gif',
    quantityBox: 'EST-18',
    quant: '900000000',
    removeClass: 'Button',
    search: 'parrot',
    cardTy: 'Visa',
    cardNum: '999 9999 9999 9999',
    expiryD: '12/03',
    firstN: 'Emir',
    lastN: 'Kovac',
    ad1: 'Tome Mendesa 31',
    ad2: '.fqasddas',
    city: 'Vogosca',
    state: 'Sarajevo',
    zip: '71320',
    country: 'United States',
    dogsSrc: '../images/dogs_icon.gif',
}