export const TestData = {
    site: 'https://petstore.octoperf.com/actions/Catalog.action',
    username: `2002`,
    password: `Emir123`,
    productId: 'AV-CB-01',
    alt: 'Birds',
    src: '#SidebarContent > a:nth-child(1) > img',
    quant: '3',
    search: 'parrot',
    cardTy: 'Visa',
    cardNum: '999 9999 9999 9999',
    expiryD: '12/03',
    firstN: 'Emir',
    lastN: 'Kovac',
    ad1: 'Tome Mendesa 31',
    ad2: '.fqasddas',
    city: 'Vogosca',
    state: 'Sarajevo',
    zip: '71320',
    country: 'United States',
}